### PR TITLE
BLDKCMF-31: Compliance Tidy-Up in BundleGen

### PR DESCRIPTION
**Pull request by mallikarjuna54**

### CODE REVIEW

**Comment by jamcoole** [comment]
Hi @mallikarjuna54  why are you using https://jira.rdkcentral.com/jira/browse/BD-963 as it is closed ? also why are you removing the consult red apache headers and adding non apache LGI ? this contradicts the LICENSE/NOTICE FILE

**Comment by mhughesacn** [comment]
Hi Mallikarjuna,
You said on Slack:
"bcatrysse requested above change request .."
So I presume that Bart asked for LGI's contribution to be properly acknowledged.  This is fine, but BundleGen is an opensourced component so you can't use a proprietary header.  Instead, please change the pre-existing lines 3-6 to use "Copyright 2021 Liberty Global"
and leave the rest.  You can ask Bart to review the pull req.

**Comment by bcatrysse** [comment]
Indeed I requested that change.
change is ok for me, thanks

**Review by mhughesacn — APPROVED** [review]
Approving because Bart has approved these changes.

**Comment by mhughesacn** [comment]
Merging as Mallikarjuna is not available, and these are trivial header updates approved by Bart Catrysse (LGI)

**Pull request merged**
