### PR TITLE
Add possibility to set DobbyInit path.

### PR DESCRIPTION
**Pull request by marcin-hajkowski-epam**

### CODE REVIEW

**Comment by TeknoVenus** [comment]
Hey @marcin-hajkowski-epam 

Is there a reason this is a runtime argument and not part of the platform template? To me, this would be a per-platform path so would be better set in the platform template json.

**Comment by marcin-hajkowski-epam** [comment]
Hi @TeknoVenus. Move it to platform template sounds reasonable, would you suggest to place it in 'mounts' section (as additional mount which will be checked if default path can be used) or platform config should be extended.

**Comment by TeknoVenus** [comment]
There's already a `dobby` section in the template that can be used to add mounts for plugins if needed for the startContainer hook (when used)

```
"dobby": {
        "pluginDir": "/usr/lib/plugins/dobby",
        "pluginDependencies": []
    }
```

I'd suggest adding a new option in that section for `dobbyInitPath`

**Review by TeknoVenus — APPROVED** [review]
LGTM

**Pull request merged**
